// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "example/template/rest_server/api/models"
	payloads "example/template/rest_server/api/users/payloads"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Begin2faSetupSession mocks base method.
func (m *MockController) Begin2faSetupSession(ctx context.Context, currentUser *models.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin2faSetupSession", ctx, currentUser)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin2faSetupSession indicates an expected call of Begin2faSetupSession.
func (mr *MockControllerMockRecorder) Begin2faSetupSession(ctx, currentUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin2faSetupSession", reflect.TypeOf((*MockController)(nil).Begin2faSetupSession), ctx, currentUser)
}

// Complete2faSetup mocks base method.
func (m *MockController) Complete2faSetup(ctx context.Context, complete2faSetupRequest *payloads.Complete2faSetupRequest, currentUser *models.User) ([]*models.RecoveryCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete2faSetup", ctx, complete2faSetupRequest, currentUser)
	ret0, _ := ret[0].([]*models.RecoveryCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete2faSetup indicates an expected call of Complete2faSetup.
func (mr *MockControllerMockRecorder) Complete2faSetup(ctx, complete2faSetupRequest, currentUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete2faSetup", reflect.TypeOf((*MockController)(nil).Complete2faSetup), ctx, complete2faSetupRequest, currentUser)
}

// CreateUser mocks base method.
func (m *MockController) CreateUser(ctx context.Context, user *payloads.CreateUserRequest) (*models.UserWithToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*models.UserWithToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockControllerMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockController)(nil).CreateUser), ctx, user)
}

// Disable2fa mocks base method.
func (m *MockController) Disable2fa(ctx context.Context, currentUser *models.User, disable2faRequest *payloads.Disable2faRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable2fa", ctx, currentUser, disable2faRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable2fa indicates an expected call of Disable2fa.
func (mr *MockControllerMockRecorder) Disable2fa(ctx, currentUser, disable2faRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable2fa", reflect.TypeOf((*MockController)(nil).Disable2fa), ctx, currentUser, disable2faRequest)
}

// Login mocks base method.
func (m *MockController) Login(ctx context.Context, user *models.User) (*payloads.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(*payloads.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockControllerMockRecorder) Login(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockController)(nil).Login), ctx, user)
}

// RegenerateRecoveryCodes mocks base method.
func (m *MockController) RegenerateRecoveryCodes(ctx context.Context, currentUser *models.User) ([]*models.RecoveryCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegenerateRecoveryCodes", ctx, currentUser)
	ret0, _ := ret[0].([]*models.RecoveryCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegenerateRecoveryCodes indicates an expected call of RegenerateRecoveryCodes.
func (mr *MockControllerMockRecorder) RegenerateRecoveryCodes(ctx, currentUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegenerateRecoveryCodes", reflect.TypeOf((*MockController)(nil).RegenerateRecoveryCodes), ctx, currentUser)
}

// UpdatePassword mocks base method.
func (m *MockController) UpdatePassword(ctx context.Context, currentUser *models.User, updatePasswordRequest *payloads.UpdatePasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, currentUser, updatePasswordRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockControllerMockRecorder) UpdatePassword(ctx, currentUser, updatePasswordRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockController)(nil).UpdatePassword), ctx, currentUser, updatePasswordRequest)
}

// VerifyLogin mocks base method.
func (m *MockController) VerifyLogin(ctx context.Context, verifyLoginRequest *payloads.LoginWithOptCodeRequest) (*payloads.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyLogin", ctx, verifyLoginRequest)
	ret0, _ := ret[0].(*payloads.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyLogin indicates an expected call of VerifyLogin.
func (mr *MockControllerMockRecorder) VerifyLogin(ctx, verifyLoginRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyLogin", reflect.TypeOf((*MockController)(nil).VerifyLogin), ctx, verifyLoginRequest)
}

// VerifyLoginWithRecoveryCode mocks base method.
func (m *MockController) VerifyLoginWithRecoveryCode(ctx context.Context, verifyLoginRequest *payloads.LoginWithRecoveryCodeRequest) (*payloads.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyLoginWithRecoveryCode", ctx, verifyLoginRequest)
	ret0, _ := ret[0].(*payloads.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyLoginWithRecoveryCode indicates an expected call of VerifyLoginWithRecoveryCode.
func (mr *MockControllerMockRecorder) VerifyLoginWithRecoveryCode(ctx, verifyLoginRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyLoginWithRecoveryCode", reflect.TypeOf((*MockController)(nil).VerifyLoginWithRecoveryCode), ctx, verifyLoginRequest)
}
