// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	db "example/template/rest_server/api/db"
	models "example/template/rest_server/api/models"
	users "example/template/rest_server/api/users"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Create2faSetupSession mocks base method.
func (m *MockStore) Create2faSetupSession(ctx context.Context, session *models.TwoFactorSetupSession) (*models.TwoFactorSetupSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create2faSetupSession", ctx, session)
	ret0, _ := ret[0].(*models.TwoFactorSetupSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create2faSetupSession indicates an expected call of Create2faSetupSession.
func (mr *MockStoreMockRecorder) Create2faSetupSession(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create2faSetupSession", reflect.TypeOf((*MockStore)(nil).Create2faSetupSession), ctx, session)
}

// CreateLoginSession mocks base method.
func (m *MockStore) CreateLoginSession(ctx context.Context, userId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoginSession", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoginSession indicates an expected call of CreateLoginSession.
func (mr *MockStoreMockRecorder) CreateLoginSession(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoginSession", reflect.TypeOf((*MockStore)(nil).CreateLoginSession), ctx, userId)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, user)
}

// Delete2faSetupSession mocks base method.
func (m *MockStore) Delete2faSetupSession(ctx context.Context, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete2faSetupSession", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete2faSetupSession indicates an expected call of Delete2faSetupSession.
func (mr *MockStoreMockRecorder) Delete2faSetupSession(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete2faSetupSession", reflect.TypeOf((*MockStore)(nil).Delete2faSetupSession), ctx, userId)
}

// DeleteLoginSessionByUserId mocks base method.
func (m *MockStore) DeleteLoginSessionByUserId(ctx context.Context, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoginSessionByUserId", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoginSessionByUserId indicates an expected call of DeleteLoginSessionByUserId.
func (mr *MockStoreMockRecorder) DeleteLoginSessionByUserId(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoginSessionByUserId", reflect.TypeOf((*MockStore)(nil).DeleteLoginSessionByUserId), ctx, userId)
}

// DeleteRecoveryCodes mocks base method.
func (m *MockStore) DeleteRecoveryCodes(ctx context.Context, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecoveryCodes", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecoveryCodes indicates an expected call of DeleteRecoveryCodes.
func (mr *MockStoreMockRecorder) DeleteRecoveryCodes(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecoveryCodes", reflect.TypeOf((*MockStore)(nil).DeleteRecoveryCodes), ctx, userId)
}

// DisableTwoFactorAuth mocks base method.
func (m *MockStore) DisableTwoFactorAuth(ctx context.Context, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTwoFactorAuth", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableTwoFactorAuth indicates an expected call of DisableTwoFactorAuth.
func (mr *MockStoreMockRecorder) DisableTwoFactorAuth(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTwoFactorAuth", reflect.TypeOf((*MockStore)(nil).DisableTwoFactorAuth), ctx, userId)
}

// EnableTwoFactorAuth mocks base method.
func (m *MockStore) EnableTwoFactorAuth(ctx context.Context, setupSession *models.TwoFactorSetupSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableTwoFactorAuth", ctx, setupSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableTwoFactorAuth indicates an expected call of EnableTwoFactorAuth.
func (mr *MockStoreMockRecorder) EnableTwoFactorAuth(ctx, setupSession interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableTwoFactorAuth", reflect.TypeOf((*MockStore)(nil).EnableTwoFactorAuth), ctx, setupSession)
}

// GenerateRecoveryCode mocks base method.
func (m *MockStore) GenerateRecoveryCode(ctx context.Context, userId int) (*models.RecoveryCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRecoveryCode", ctx, userId)
	ret0, _ := ret[0].(*models.RecoveryCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRecoveryCode indicates an expected call of GenerateRecoveryCode.
func (mr *MockStoreMockRecorder) GenerateRecoveryCode(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRecoveryCode", reflect.TypeOf((*MockStore)(nil).GenerateRecoveryCode), ctx, userId)
}

// Get2faSetupSessionByUserId mocks base method.
func (m *MockStore) Get2faSetupSessionByUserId(ctx context.Context, userId int) (*models.TwoFactorSetupSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get2faSetupSessionByUserId", ctx, userId)
	ret0, _ := ret[0].(*models.TwoFactorSetupSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get2faSetupSessionByUserId indicates an expected call of Get2faSetupSessionByUserId.
func (mr *MockStoreMockRecorder) Get2faSetupSessionByUserId(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get2faSetupSessionByUserId", reflect.TypeOf((*MockStore)(nil).Get2faSetupSessionByUserId), ctx, userId)
}

// GetLoginSessionById mocks base method.
func (m *MockStore) GetLoginSessionById(ctx context.Context, loginSessionId int) (*models.LoginSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginSessionById", ctx, loginSessionId)
	ret0, _ := ret[0].(*models.LoginSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginSessionById indicates an expected call of GetLoginSessionById.
func (mr *MockStoreMockRecorder) GetLoginSessionById(ctx, loginSessionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginSessionById", reflect.TypeOf((*MockStore)(nil).GetLoginSessionById), ctx, loginSessionId)
}

// GetRecoveryCodesByUserId mocks base method.
func (m *MockStore) GetRecoveryCodesByUserId(ctx context.Context, userId int) ([]*models.RecoveryCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecoveryCodesByUserId", ctx, userId)
	ret0, _ := ret[0].([]*models.RecoveryCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecoveryCodesByUserId indicates an expected call of GetRecoveryCodesByUserId.
func (mr *MockStoreMockRecorder) GetRecoveryCodesByUserId(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecoveryCodesByUserId", reflect.TypeOf((*MockStore)(nil).GetRecoveryCodesByUserId), ctx, userId)
}

// GetUserById mocks base method.
func (m *MockStore) GetUserById(ctx context.Context, userId int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, userId)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockStoreMockRecorder) GetUserById(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockStore)(nil).GetUserById), ctx, userId)
}

// GetUserByUsername mocks base method.
func (m *MockStore) GetUserByUsername(ctx context.Context, username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStoreMockRecorder) GetUserByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStore)(nil).GetUserByUsername), ctx, username)
}

// RedeemRecoveryCode mocks base method.
func (m *MockStore) RedeemRecoveryCode(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemRecoveryCode", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedeemRecoveryCode indicates an expected call of RedeemRecoveryCode.
func (mr *MockStoreMockRecorder) RedeemRecoveryCode(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemRecoveryCode", reflect.TypeOf((*MockStore)(nil).RedeemRecoveryCode), ctx, id)
}

// UpdatePassword mocks base method.
func (m *MockStore) UpdatePassword(ctx context.Context, password string, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, password, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockStoreMockRecorder) UpdatePassword(ctx, password, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockStore)(nil).UpdatePassword), ctx, password, userId)
}

// WithQuerier mocks base method.
func (m *MockStore) WithQuerier(q db.Querier) users.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithQuerier", q)
	ret0, _ := ret[0].(users.Store)
	return ret0
}

// WithQuerier indicates an expected call of WithQuerier.
func (mr *MockStoreMockRecorder) WithQuerier(q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithQuerier", reflect.TypeOf((*MockStore)(nil).WithQuerier), q)
}
