// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	middleware "example/template/rest_server/api/middleware"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMiddleWareManager is a mock of MiddleWareManager interface.
type MockMiddleWareManager struct {
	ctrl     *gomock.Controller
	recorder *MockMiddleWareManagerMockRecorder
}

// MockMiddleWareManagerMockRecorder is the mock recorder for MockMiddleWareManager.
type MockMiddleWareManagerMockRecorder struct {
	mock *MockMiddleWareManager
}

// NewMockMiddleWareManager creates a new mock instance.
func NewMockMiddleWareManager(ctrl *gomock.Controller) *MockMiddleWareManager {
	mock := &MockMiddleWareManager{ctrl: ctrl}
	mock.recorder = &MockMiddleWareManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleWareManager) EXPECT() *MockMiddleWareManagerMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockMiddleWareManager) Auth(next http.HandlerFunc) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", next)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockMiddleWareManagerMockRecorder) Auth(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockMiddleWareManager)(nil).Auth), next)
}

// CompileMiddlewares mocks base method.
func (m *MockMiddleWareManager) CompileMiddlewares(h http.HandlerFunc, args ...middleware.Middleware) http.HandlerFunc {
	m.ctrl.T.Helper()
	varargs := []interface{}{h}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CompileMiddlewares", varargs...)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// CompileMiddlewares indicates an expected call of CompileMiddlewares.
func (mr *MockMiddleWareManagerMockRecorder) CompileMiddlewares(h interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{h}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompileMiddlewares", reflect.TypeOf((*MockMiddleWareManager)(nil).CompileMiddlewares), varargs...)
}

// Cors mocks base method.
func (m *MockMiddleWareManager) Cors(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cors", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Cors indicates an expected call of Cors.
func (mr *MockMiddleWareManagerMockRecorder) Cors(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cors", reflect.TypeOf((*MockMiddleWareManager)(nil).Cors), next)
}
